<?php
/**
 * Created by PhpStorm.
 * User: masterpc
 * Date: 17-4-11
 * Time: 下午10:25
 */

namespace backend\controllers;

use Yii;
use yii\web\ForbiddenHttpException;

class BaseController extends \yii\web\Controller
{
    public $ignoreList = ['admin/*', 'merchant/*'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        //如果未登录，则直接返回
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        //获取路径
        $path = Yii::$app->request->pathInfo;
        //var_dump($path);
        //忽略列表
        if (in_array($path, $this->ignoreList)) {
            return true;
        }
        $path = '/' . $path;

        if (Yii::$app->user->can($path)) {
            return true;
        } else {
            throw new ForbiddenHttpException(Yii::t('app', 'message 401'));
        }

        // return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}