<?php

namespace common\models;

use Yii;
use yii\base\Model;
use backend\models\Merchant;

/**
 * Login form
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user;


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, '无效的用户名和密码.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     *
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            //return   self::chekIsAuthored();
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 * 30 : 0);
        } else {
            return false;
        }
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    protected function getUser()
    {
        if ($this->_user === null) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }

    /**
     * 商户验证通过审核
     * @return bool
     */
    protected function chekIsAuthored()
    {
        $model = Merchant::findOne(['uid' => self::getUser()->id]);
        if (isset($model) && $model->status_acount == '通过') {
            return true;
        }
        return false;
    }

    public function attributeLabels()
    {
        $attributes = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $attributes['password'] = '登录密码';
        $attributes['username'] = '商户账号';
        return $attributes;

    }
}
